version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: coverage run -m unittest && coverage xml && coverage report -m
      - run:
          name: Upload CodeClimate coverage report
          command: |
            ./cc-test-reporter after-build -- f14fa0f8f9d53eae9c6241817f4ac7d9cc415c1e8b8f5ca6926e78d3000bfe7f
